export interface Founder {
  name: string;
  role: string;
  image: string;
  bio: string;
  linkedin?: string;
  twitter?: string;
}

export interface Startup {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  product?: string;
  logo: string;
  batch: string;
  industry: string;
  website: string;
  tags: string[];
  founders: Founder[];
  stage?: string;
}

export const startups: Startup[] = [
  {
    id: "summit",
    name: "Summit",
    description: "Optimizing the AI search engine for rising businesses.",
    longDescription:
      "Summit helps give companies visibility to how they show up on AIs like ChatGPT, Perplexity, Claude and Gemini. By providing insights on where companies show amongst competitors in similar spaces, Summit targets niches to regain and provides steps to increase visibility to pop up on more answers on AI.",
    product:
      "Summit provides a scope of the competition space by starting out with a URL and some basic questions. Users then receive insights on where their company stands on AI search results in comparison to competitors. From there, recommendations and plans of action are given to increase AI visibility to show up higher and more frequently on search results.",
    logo: "/startup-logos/summit.png",
    batch: "F25",
    industry: "AI/ML",
    website: "https://summit-geo.net/",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Lucas Rival",
        role: "PM",
        image: "/founders/f25/lucas.png",
        bio: "MechE @ USC. With wide background in propulsion systems and startups, Lucas pushes the line of fast paced innovation with a technical background.",
        linkedin: "https://www.linkedin.com/in/lucasrival/",
      },
      {
        name: "Jo Choi",
        role: "Designer",
        image: "/founders/f25/jo.png",
        bio: "PR & Advertising @ USC. With backgrounds in entertainment, marketing, and startups, he is a product designer committed to creating cool consumer experiences.",
        linkedin: "https://www.linkedin.com/in/joseph-choi-051b8a288/",
      },
      {
        name: "Ka'ren Mkrtchyan",
        role: "Developer",
        image: "/founders/f25/karen.png",
        bio: "CECS @ USC. Karen is a published author in the AI space, encompassing AI with hardware and robotics.",
        linkedin: "https://www.linkedin.com/in/karenmkr/",
      },
      {
        name: "Amir Mamoon",
        role: "Developer",
        image: "/founders/f25/amir.png",
        bio: "CS @ USC. Previously software engineer at Ticketmaster.",
        linkedin: "https://www.linkedin.com/in/mohamed-mamoon/",
      },
    ],
  },
  {
    id: "zeno",
    name: "Zeno",
    description: "Satellite operations copilot for incident management.",
    longDescription:
      "Satellite operators today rely on fragmented dashboards, logs, and documentation to diagnose issues across complex spacecraft systems. When anomalies occur, engineers often spend days or weeks manually tracing signals across subsystems to identify the root cause. This process slows incident resolution, risks mission downtime, and becomes increasingly unsustainable as satellite fleets scale. Zeno is an AI-powered operations copilot designed to help satellite engineers investigate and resolve incidents faster. By automatically aggregating telemetry, system logs, and operational documentation, Zeno surfaces patterns and anomalies across subsystems that would otherwise take engineers weeks to uncover. This enables teams to identify root causes earlier, reduce downtime, and operate larger satellite fleets without proportionally increasing operations staff.",
    product:
      "Zeno provides an intelligent incident management workspace for satellite operations teams. When anomalies occur, the platform automatically creates an incident, analyzes telemetry data across subsystems, and surfaces relevant logs, historical incidents, and engineering documentation. Using machine learning to detect deviations from normal satellite behavior, Zeno highlights potential causes and guides engineers through diagnostic workflows. Engineers can collaborate within the platform to investigate issues, document findings, and update operational checklists for future incidents. Over time, Zeno builds a knowledge base of mission operations, enabling faster troubleshooting and predictive maintenance across satellite fleets.",
    logo: "/startup-logos/zeno.png",
    batch: "F25",
    industry: "Aerospace",
    website: "https://www.zeno.so/",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Sebastian Sampedro",
        role: "PM",
        image: "/founders/f25/sebastian.png",
        bio: "Sebastian studies philosophy at USC. He leads research and investments at Blockchain at USC and has worked across crypto, growth, and venture.",
        linkedin: "https://www.linkedin.com/in/sxsampedro/",
      },
      {
        name: "Allison Wong",
        role: "Designer",
        image: "/founders/f25/allison.png",
        bio: "Allison is a multidisciplinary designer working across graphics, product, interaction, apparel, and experience design. Previously, Allison has worked with BMW Designworks, Beats by Dre, and Yahoo, where she explored the intersection of design, culture, and innovation. She is currently the Co-Founder and Creative Director of AC Unit, a fashion and hardware brand blending physical products with conceptual storytelling.",
        linkedin: "https://www.linkedin.com/in/allisonwong05/",
      },
      {
        name: "Shiven Dabhi",
        role: "Developer",
        image: "/founders/f25/shiven.png",
        bio: "Shiven studies aerospace engineering at USC. He is the founder of OpusList, an ML-powered time management platform, and builds at the intersection of aerospace and AI.",
        linkedin: "https://www.linkedin.com/in/shiven-dabhi/",
      },
      {
        name: "Pan Pitpreecha",
        role: "Developer",
        image: "/founders/f25/pan.png",
        bio: "Pan has engineering experience working across electrical systems, robotics, and IoT. He brings a hardware-first perspective, applying a technical approach to agricultural tools, airborne objects, and physical AI. Additionally, he specializes in agentic AI orchestration for frontend design of websites and apps. Previously, Pan has worked in a student intern program at AWS, with experience in cloud systems and client management.",
        linkedin: "https://www.linkedin.com/in/pitpreec/",
      },
    ],
  },
  {
    id: "basis",
    name: "Basis",
    description: "Accelerated Depreciation, Made Simple.",
    longDescription:
      "Basis is an AI-powered platform that streamlines cost segregation studies by tackling the most time-intensive step: analyzing property data across photos, sketches, and appraisal documents. By structuring and interpreting this information, Basis helps teams produce accurate, IRS-ready reports faster. Rather than replacing engineers, it embeds a human-in-the-loop workflow that guides decisions, reduces manual review time, and improves consistency across studies.",
    product:
      "Basis provides a structured workflow for cost segregation teams. Engineers upload the property artifacts they already use, and the platform organizes documents, extracts key information, and surfaces relevant classifications and references. It guides users through each step of the review process, highlights what matters for tax treatment, and ensures that every decision is traceable. Teams can move faster, reduce time spent searching across documents, and maintain a clear, auditable record of their work.",
    logo: "/startup-logos/basis.png",
    batch: "F25",
    industry: "Tax",
    website: "",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Noah Howard",
        role: "PM",
        image: "/founders/f25/noah.png",
        bio: "Incoming IB analyst @ Citibank. Noah’s experience lies at the intersection of strategy and finance, with emphasis on data, growth, and GTM.",
        linkedin: "https://www.linkedin.com/in/howard-noah/",
      },
      {
        name: "Shreya Shanmugam",
        role: "Designer",
        image: "/founders/f25/shreya.png",
        bio: "Product-minded designer working at the intersection of UX and business strategy. Shreya has experience building and launching products with a focus on growth, rapid iteration, and translating user insights into scalable solutions.",
        linkedin: "https://www.linkedin.com/in/shreyaa-shanmugam/",
        twitter: "https://x.com/ShanmugamS84811",
      },
      {
        name: "Adrian Thomas",
        role: "Developer",
        image: "/founders/f25/adrian.png",
        bio: "Incoming @ Google. Adrian has experience building products across systems, infrastructure, and automation, and led product development for a desktop app that generated over $200K in revenue. He is currently focused on distributed systems research.",
        linkedin: "http://linkedin.com/in/adrianth",
        twitter: "https://x.com/PradaShady",
      },
      {
        name: "Bryan Ramirez-Gonzalez",
        role: "Developer",
        image: "/founders/f25/bryan.png",
        bio: "Bryan studies CS at USC. Incoming SWE intern at NVIDIA working on agentic systems, with research experience in multimodal AI and published work (ICWSM).",
        linkedin: "https://www.linkedin.com/in/bryanrg22/",
      },
    ],
  },
  {
    id: "ivory",
    name: "Ivory",
    description: "Giving buying power back to dental practices.",
    longDescription:
      "Ivory starts as an AI native inventory platform connected to dentists’ patient management software.",
    product:
      "Ivory automates dental supply purchasing for single practitioners, handling cart building, order placement, and live inventory tracking. As the network grows, Ivory aggregates purchasing data across practitioners and uses collective buying power to negotiate lower prices with distributors like Patterson Dental. Solo practices get the same pricing leverage that large dental groups already enjoy.",
    logo: "/startup-logos/ivory.png",
    batch: "F25",
    industry: "AI/ML",
    website: "",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Mannat Bawa",
        role: "PM",
        image: "/founders/f25/mannat.png",
        bio: "CS at USC (Trustee Scholar). PM for Ivory (AI inventory platform). Previously SWE intern at Northrop Grumman.",
        linkedin: "https://www.linkedin.com/in/mannatbawa/",
      },
      {
        name: "Olivia Nazari",
        role: "Designer",
        image: "/founders/f25/olivia.png",
        bio: "Olivia is the Head of Marketing and Operations at Emanate, a unicorn startup (1.2B valuation) out of a16z speedrun, with investors from Peter Thiel and Alexis Ohanian. Previously, she was Head of Design at Algorhythm, where she led product and brand direction for a music marketing research platform serving Sony AWAL and Warner Music, helping grow the company to a $500K pre-seed raise. Olivia studied Design at USC and Animation at CSSSA.",
        linkedin: "https://www.linkedin.com/in/olivia-nazari/",
      },
      {
        name: "Kenneth Choi",
        role: "Developer",
        image: "/founders/f25/kenneth.png",
        bio: "AI @ USC | YCombinator AI Hackathon Winner | prev. Arthub, Stanford AIMI",
        linkedin: "https://www.linkedin.com/in/kenneth-choi-1859b21bb/",
      },
      {
        name: "May Khan",
        role: "Developer",
        image: "/founders/f25/may.png",
        bio: "CECS at USC (Merit Scholar). Incoming at Medtronic.",
        linkedin: "https://www.linkedin.com/in/maymoonakhan/",
      },
    ],
  },
  {
    id: "pillar",
    name: "Pillar",
    description: "Customized AI Copilot for Preconstruction.",
    longDescription:
      "Pillar addresses inefficiencies in preconstruction, where contractors must analyze complex blueprints and produce accurate cost estimates under tight deadlines. Today, estimators rely on manual takeoffs and incomplete pricing data, leading to inaccurate bids and financial risk. These inefficiencies result in lost contracts or reduced margins across the industry. Pillar focuses on improving speed, accuracy, and workflow alignment in the estimation process.",
    product:
      "Pillar is a customized AI-powered copilot for preconstruction that automates material takeoffs from uploaded blueprints. It enables teams to validate quantities, reach out to vendors, and receive real-time pricing data within a single workflow. Pillar adapts to each contractor’s workflow through modular features, allowing teams to use only what they need.",
    logo: "/startup-logos/pillar.png",
    batch: "F25",
    industry: "Construction",
    website: "https://youtu.be/0vhIymZsygU",
    tags: ["AI", "B2B", "Construction"],
    stage: "",
    founders: [
      {
        name: "Sumin Wu",
        role: "PM",
        image: "/founders/f25/sumin.png",
        bio: "Incoming Product Marketing @Amex, prev AI Marketing & Strategy @Verizon. Sumin’s prior experience involves co-founding and scaling Hemut (YC X25) alongside AI research for Greece’s 2025 AI national policy.",
        linkedin: "https://www.linkedin.com/in/sumin-wu-bxn/",
      },
      {
        name: "Joshua Placido",
        role: "Designer",
        image: "/founders/f25/joshua.png",
        bio: "Josh is a product designer building communities and experiences at a human tempo. Currently leading UI/UX design at Preface Health for 1M+ patients, working directly with founders to strengthen product direction. His experience lies at the intersection of AI, healthcare and music.",
        linkedin: "https://www.linkedin.com/in/joshua-placido/",
      },
      {
        name: "Wesley Chou",
        role: "Developer",
        image: "/founders/f25/wesley.png",
        bio: "Software Engineering Intern at Tesla. Previously interned at Paramount and Sony.",
        linkedin: "https://www.linkedin.com/in/wesley-chou-713640235/",
      },
      {
        name: "Tiffanie Lim",
        role: "Developer",
        image: "/founders/f25/tiffanie.png",
        bio: "Incoming SWE @ Snap Inc. Experience building full-stack applications and backend systems, with an interest in product-driven development.",
        linkedin: "https://www.linkedin.com/in/tiffanielim/",
      },
    ],
  },
  {
    id: "accolade",
    name: "Accolade",
    description: "The unified workspace for college counseling.",
    longDescription:
      "Accolade provides a counselor-first CRM that organizes everything happening across all students. Counselors are burdened by disconnected tools, wasting hours manually piecing things together instead of supporting students effectively. Instead of seven browser tabs, Accolade is one AI-native workspace that takes care of busy administrative work so counselors can focus on what matters: getting their students into college.",
    product:
      "Accolade consolidates documents and college information for each student, providing analytics and suggestions through industry-standard integrations while improving communication with meeting bookings and reminders. Students, parents, and counselors each have role-specific interfaces tailored to their needs, keeping every stakeholder in the loop.",
    logo: "/startup-logos/accolade.png",
    batch: "F25",
    industry: "EdTech",
    website: "",
    tags: ["AI", "B2C", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Landon Cao",
        role: "PM",
        image: "/founders/f25/landon.png",
        bio: "GTM @ super{set}, prev. Account Executive at Hemut (YC X25), Focused on Sales, Business Development, and GTM Strategy for various companies.",
        linkedin: "https://www.linkedin.com/in/landon-cao/",
      },
      {
        name: "Jeslyn Chun",
        role: "Designer",
        image: "/founders/f25/jeslyn.png",
        bio: "Jeslyn is a product designer at USC. She has designed across startups including BCombs and Whealthy.",
        linkedin: "https://www.linkedin.com/in/jeslynchun/",
      },
      {
        name: "Mark McGuire",
        role: "Developer",
        image: "/founders/f25/mark.png",
        bio: "SWE @ SpaceX, I was previously a founding engineer at PARES (YC S25). Right now I’m focused on space, robotics, RL, and building for the agentic future.",
        linkedin: "https://www.linkedin.com/in/mark-mcguire011/",
        twitter: "https://x.com/markmcguire123",
      },
    ],
  },
  {
    id: "helios",
    name: "Helios",
    description: "Streamlining early-stage drug discovery.",
    longDescription:
      "Helios is an AI-powered platform that helps drug discovery teams identify which compounds are worth testing before costly lab validation. Early-stage drug development is defined by uncertainty, where scientists must evaluate thousands of candidates across critical factors like toxicity, stability, and target binding, yet have no reliable way to do so without slow and expensive experiments. As a result, over 90% of drug candidates fail during hit-to-lead optimization, often after months of work and significant capital have already been spent. Advances in AI have only increased the number of potential candidates, intensifying this bottleneck and causing teams to waste 6-18 months and hundreds of thousands of dollars pursuing the wrong compounds and delaying life-saving breakthroughs.",
    product:
      "Helios provides a predictive workflow for early-stage drug discovery, enabling scientists to evaluate and prioritize compounds before entering the lab. Users upload candidate compounds, and the platform analyzes molecular structure and behavior to generate predictions on key properties such as toxicity, stability, and target binding. Helios augments these insights with evidence from structurally similar compounds and their known experimental outcomes, giving researchers clear, data-backed context for decision-making. By allowing teams to filter, compare, and confidently select the most promising candidates, Helios reduces unnecessary testing, accelerates iteration cycles, and helps bring effective therapies to market faster.",
    logo: "/startup-logos/helios.png",
    batch: "F25",
    industry: "Healthcare",
    website: "",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Nabeel Trimzi",
        role: "PM",
        image: "/founders/f25/nabeel.png",
        bio: "Presidential Scholar at USC studying neuroscience and business finance, building at the intersection of neuromodulation, medicine, and biotech.",
        linkedin: "https://www.linkedin.com/in/nabeeltrimzi/",
      },
      {
        name: "Heather Liu",
        role: "Designer",
        image: "/founders/f25/heather.png",
        bio: "Heather studies cognitive science at USC and is a product designer focused on healthcare systems. She has worked at Blue Shield and across early-stage startups.",
        linkedin: "https://www.linkedin.com/in/heather-liu/",
      },
      {
        name: "Parker Gurney",
        role: "Developer",
        image: "/founders/f25/parker.png",
        bio: "Parker studies computer science at USC. She is a developer at Perfit and previously worked on data systems and infrastructure at startups.",
        linkedin: "https://www.linkedin.com/in/parkergurney/",
      },
      {
        name: "Sanjna Sunil",
        role: "Developer",
        image: "/founders/f25/sanjna.png",
        bio: "Sanjna studies CECS at USC. Previously interned at PayPal. Builds across full-stack systems and product.",
        linkedin: "https://www.linkedin.com/in/sanjna-sunil26/",
      },
    ],
  },
  {
    id: "Oasis",
    name: "Oasis",
    description: "Revolutionizing at-home elderly care with vision-based AI.",
    longDescription:
      "Oasis is a vision-first hardware company focused on enabling independent living for the elderly. Our product ecosystem uses secure, on-device vision AI to detect critical events including falls, respiratory distress, and calls for help, in real time. By operating entirely on-device, Oasis preserves user privacy while eliminating high recurring subscription costs. Unlike traditional 'band-aid solutions' such as using baby monitors or emergency buttons (which rely on active use or constant supervision), Oasis provides continuous, passive monitoring. We deliver timely intervention and greater peace of mind for families without compromising dignity or independence.",
    product:
      "Oasis is a hardware ecosystem for family homes that uses vision-based AI techniques to detect dangerous events (such as falls, respiratory distress, and calls for help). Our algorithm implements research-backed approaches to identify and characterize these events in real time, and notify family members or emergency services. Calculations are performed on-device in real time, providing complete data security, reliable detection, and economical operation. Oasis is the first to introduce these exciting new computer vision techniques to the consumer market.",
    logo: "/startup-logos/oasis.png",
    batch: "S25",
    industry: "Consumer",
    website: "",
    tags: ["AI", "Elder Care", "Hardware"],
    stage: "",
    founders: [
      {
        name: "Jasmita Yechuri",
        role: "PM",
        image: "/founders/s25/jasmita.png",
        bio: "Jasmita is a Computer Science and Business major at USC, and the PM for OASIS during the Spring 2025 cohort. She enjoys building human centered products that use technology to solve real-world problems and create meaningful social impact. Outside of work and school, she enjoys baking, traveling, collecting stuffed animals from claw machines, and listening to k-pop!",
        linkedin: "https://www.linkedin.com/in/jasmita-yechuri/",
      },
      {
        name: "Teri Shim",
        role: "Designer",
        image: "/founders/s25/teri.png",
        bio: "Teri is a product designer @ USC IYA. She previously worked as a UX Design Intern @ National Geographic Society",
        linkedin: "https://www.linkedin.com/in/teri-shim/",
      },
      {
        name: "Ethan Palosh",
        role: "Developer",
        image: "/founders/s25/ethan.png",
        bio: "Ethan Palosh is the Director of Development at LavaLab, leading all engineering curriculum and mentorship. At USC, he is pursuing a B.S. in Computer Engineering (CECS) and a M.S. in Computer Science. Outside of school, he loves pickleball, motorsports, and trying new restaurants!",
        linkedin: "https://www.linkedin.com/in/ethanpalosh/",
      },
      {
        name: "Ashvin Arora",
        role: "Developer",
        image: "/founders/s25/ashvin.png",
        bio: "Ashvin studies Computer Engineering and Computer Science at USC. He was a dev in LavaLab's S25 cohort working on OASIS. Outside of Lava, he enjoys playing soccer, eating, and traveling.",
        linkedin: "https://www.linkedin.com/in/ashvin-arora/",
      },
    ],
  },
  {
    id: "structure",
    name: "Structure",
    description: "Compliance copilot for architects.",
    longDescription:
      "Structure is an AI-powered platform that reviews architectural drawings against zoning and building code requirements before permit submission. By automatically flagging issues like ADA compliance gaps, Structure helps teams catch problems early. This reduces costly redesign cycles and speeds up the path to permit approval for architecture firms.",
    product:
      "Structure provides a compliance review workflow for architecture teams. Users upload plans, and the platform parses documents, checks them against regulatory rules, and highlights potential violations. Teams can collaborate on flagged issues, track fixes across iterations, and maintain a clear record of compliance decisions.",
    logo: "/startup-logos/structure.png",
    batch: "S25",
    industry: "AI/ML",
    website: "https://www.buildstructure.net/",
    tags: ["Architecture", "B2B", "Proptech"],
    stage: "",
    founders: [
      {
        name: "Arnav Shah",
        role: "PM",
        image: "/founders/s25/arnav.png",
        bio: "Business at USC, former GTM Analyst at Axal (YC W25). Building Satori at the intersection of Manufacturing and Technology. ",
        linkedin: "https://www.linkedin.com/in/arnav-ashah/",
        twitter: "https://x.com/ArnavAShah",
      },
      {
        name: "Olivia Nazari",
        role: "Designer",
        image: "/founders/s25/olivia.png",
        bio: "Olivia is the Head of Marketing and Operations at Emanate, a unicorn startup (1.2B valuation) out of a16z speedrun, with investors from Peter Thiel and Alexis Ohanian. Previously, she was Head of Design at Algorhythm, where she led product and brand direction for a music marketing research platform serving Sony AWAL and Warner Music, helping grow the company to a $500K pre-seed raise. Olivia studied Design at USC and Animation at CSSSA.",
        linkedin: "https://www.linkedin.com/in/olivia-nazari/",
      },
      {
        name: "Sonya Alexis",
        role: "Developer",
        image: "/founders/s25/sonya.png",
        bio: "Incoming SWE at Databricks. Previous SWE at Bloomberg building trading platforms. Sonya studies Computer Engineering and Computer Science at USC and is interested in distributed systems, applied AI, and hardware-software integrations.",
        linkedin: "https://www.linkedin.com/in/sonya-alexis",
        twitter: "https://x.com/sonyaalexisss",
      },
      {
        name: "Rida Faraz",
        role: "Developer",
        image: "/founders/s25/rida.png",
        bio: "Incoming AI/ML @Apple. Rida’s experience lies at the intersection of hardware devices and AI model training with special emphasis on robotics. ",
        linkedin: "https://www.linkedin.com/in/rida-faraz/",
      },
    ],
  },
  {
    id: "lily",
    name: "Lily",
    description: "AI-powered IEP progress tracking for special educators.",
    longDescription:
      "Lily is building a modern platform for special educators to streamline IEP (Individualized Education Program) progress tracking. Today, special education teachers and service providers often manage progress updates through fragmented spreadsheets, manual notes, and time-consuming documentation workflows. This creates administrative burden, makes it harder to maintain consistent records, and takes time away from supporting students. Lily simplifies this process with an AI-powered workflow designed specifically for special education teams.",
    product:
      "Lily is an AI-powered IEP progress tracking tool built for special educators. It helps teachers and providers capture student progress more efficiently, keep documentation organized, and generate clearer progress records over time. Instead of relying on scattered notes and manual workflows, educators can use Lily to streamline reporting and stay on top of each student’s goals more precisely and efficiently.",
    logo: "/startup-logos/lily.png",
    batch: "S25",
    industry: "EdTech",
    website: "https://mylily.org/",
    tags: ["SaaS", "B2B", "AI"],
    stage: "",
    founders: [
      {
        name: "Matthew Suri",
        role: "PM",
        image: "/founders/s25/matthew.png",
        bio: "Building AI-native products at the intersection of education and ML; Co-founder of Lily (IEP software), prev ML @ Warner Bros. Discovery (HBO Max) and GTM/ML @ Salesforce; MS Applied Data Science @ USC Iovine and Young Academy.",
        linkedin: "https://www.linkedin.com/in/matthewsuri/",
        twitter: "https://x.com/sum8tt",
      },
      {
        name: "Tongfei Zhu",
        role: "Designer",
        image: "/founders/s25/tongfei.png",
        bio: "Incoming Design Engineer @Emerson Collective. Design & Marketing @Chosan. Tongfei transforms abstract concepts into tangible experiences through product development and computational design.",
        linkedin: "https://www.linkedin.com/in/tongfeiz/",
        twitter: "https://x.com/tongfeizhu",
      },
      {
        name: "Pranav Lingareddy",
        role: "Developer",
        image: "/founders/s25/pranav.png",
        bio: "Forward Deployed Eng @ Nominal, prev SWE @ Amazon Web Services; Building at the intersection AI and real-world systems. Co-founder of Lily (AI-native IEP software); CS + Business @ University of Southern California",
        linkedin: "https://www.linkedin.com/in/pranav-lingareddy/",
        twitter: "https://x.com/crypiko",
      },
      {
        name: "Harry Ahn",
        role: "Developer",
        image: "/founders/s25/harry.png",
        bio: "Full-stack builder focused on scalable, user-centric products @ Dayli; Co-founder of Lily, prev SWE @ Qraft Technologies and developer @ University of Southern California; CS @ USC.",
        linkedin: "https://www.linkedin.com/in/hongsuh-ahn-b7520a188/",
      },
    ],
  },
  {
    id: "vector",
    name: "Vector",
    description: "An agentic navigator for instant, in-app support.",
    longDescription:
      "Vector helps SaaS companies solve one of their most expensive product problems: users getting stuck. When people open a new platform, they often end up lost in confusing workflows, outdated documentation, and slow support loops. This creates frustration for users and overwhelms support teams, leading to churn, lower product adoption, and lost revenue. Vector addresses this by giving companies a way to guide users in the moment they need help, so they can complete tasks instead of abandoning them.",
    product:
      "Vector is an AI co-pilot embedded directly inside a software product that helps users complete tasks in real time. Instead of sending users to help docs or support tickets, Vector lets them describe what they are trying to do, then guides or executes the workflow directly in the app. For example, if a user asks how to duplicate and customize a template, Vector can identify the right UI elements, walk through the multi-step process, and get them to the correct end state in seconds. Beyond task completion, Vector also provides analytics on where users get stuck, helping companies identify friction points and reduce support volume.",
    logo: "/startup-logos/vector.png",
    batch: "S25",
    industry: "AI/ML",
    website: "https://usevector.app/",
    tags: ["B2B", "Onboarding", "Customer Support"],
    stage: "",
    founders: [
      {
        name: "Arman Arya",
        role: "PM",
        image: "/founders/s25/arman.png",
        bio: "Incoming Investment Banking @ Moelis & Co. Arman's experience lies at the intersection of M&A advisory and venture/growth investing, with a focus on tech and media transactions.",
        linkedin: "https://www.linkedin.com/in/arman-arya/",
        twitter: "https://x.com/arman_arya1",
      },
      {
        name: "Maya Parthasarathy",
        role: "Designer",
        image: "/founders/s25/maya.png",
        bio: "Designer @ Profound, previously Growth @ Science, a CPG, VC, and venture studio. Maya’s experience centers on UX, with a focus on helping people create, navigate, and get unstuck inside digital products, especially creator tools for video and music.",
        linkedin: "https://www.linkedin.com/in/maya-parthasarathy/",
        twitter: "https://x.com/mayaparthas",
      },
      {
        name: "Brennen Ho",
        role: "Developer",
        image: "/founders/s25/brennen.png",
        bio: "Engineering @ Decagon, previously Bloomberg. Brennen is experienced creating products that simplify, accelerate, and personalize — with an emphasis on applied AI.",
        linkedin: "https://www.linkedin.com/in/brennenho/",
        twitter: "https://x.com/brennenho_",
      },
      {
        name: "Vishnu Kadaba",
        role: "Developer",
        image: "/founders/s25/vishnu.png",
        bio: "Incoming SWE Intern @ Google. Vishnu's experiences and interests lie at the intersection of ML research and Applied AI with an emphasis on full-stack apps and AI agents.",
        linkedin: "https://www.linkedin.com/in/vishnu-swarup-kadaba/",
        twitter: "https://x.com/KadabaSwar98127",
      },
    ],
  },
  {
    id: "vetrail",
    name: "Vetrail",
    description: "Digital bridge between vets and pet owners.",
    longDescription:
      "Vetrail is a client-facing platform that bridges the communication gap between veterinary clinics and pet owners. Clinics today field over 150 phone calls a day just to handle record requests, appointment updates, and lab questions — leaving staff overwhelmed and owners frustrated. Vetrail fixes this by giving pet owners instant digital access to their pet's health information, reducing the burden on clinics and improving the quality of care.",
    product:
      "Vetrail gives pet owners a secure portal to view appointments, immunization records, lab results, and billing, with AI-powered summaries that translate complex vet notes into plain language. On the clinic side, the platform integrates with existing practice management systems and provides a dashboard to streamline patient communication and record management.",
    logo: "/startup-logos/vetrail.png",
    batch: "S25",
    industry: "Healthcare",
    website: "https://www.vetrail.app/",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Arin Jain",
        role: "PM",
        image: "/founders/s25/arin.png",
        bio: "IB Analyst @ Stifel. Arin operates at the intersection of finance and entrepreneurship with a focus on early-stage venture building and capital markets.",
        linkedin: "https://www.linkedin.com/in/arinjain1/",
      },
      {
        name: "Jamie Hsu",
        role: "Designer",
        image: "/founders/s25/jamie.png",
        bio: "Product Design @ Roblox. Jamie designs at the intersection of human-centered design and AI, building products from early-stage to scaled systems with a focus on user trust and safety. ",
        linkedin: "https://www.linkedin.com/in/jamiehsuu/",
      },
      {
        name: "Andrew Choi",
        role: "Developer",
        image: "/founders/s25/andrew.png",
        bio: "Incoming SWE @ Microsoft. Andrew develops scalable full-stack and AI-driven systems, with experience building products impacting $300M+ in revenue. He’s especially interested in leveraging AI for mapping, geospatial intelligence, and urban planning.",
        linkedin: "https://www.linkedin.com/in/andrewchoi82/",
      },
      {
        name: "Jesse Tzo",
        role: "Developer",
        image: "/founders/s25/jesse.png",
        bio: "Jesse builds full-stack products with React, Node.js, and PostgreSQL. His work focuses on scalable systems and real-time applications across web platforms.",
        linkedin: "https://www.linkedin.com/in/jesse-tzo/",
      },
    ],
  },
  {
    id: "voxel",
    name: "Voxel",
    description: "Seamless patient communication with customizable voice AI for clinics.",
    longDescription:
      "Voxel is an AI-powered platform that enables clinics to build and deploy custom voice agents for patient communication. By automating appointment reminders, follow-up calls, and scheduling coordination, Voxel helps healthcare teams reduce no-shows and streamline phone workflows — freeing staff to focus on in-person care.",
    product:
      "Voxel provides a voice AI workflow for clinics and healthcare teams. Users build custom voice agents, and the platform handles outbound reminders, follow-up calls, and appointment coordination automatically. Teams can monitor call outcomes, track patient responses, and maintain a clear record of communication across every interaction.",
    logo: "/startup-logos/voxel.png",
    batch: "S25",
    industry: "Healthcare",
    website: "https://cadence-v3-seven.vercel.app/",
    tags: ["AI", "B2B", "HealthTech"],
    stage: "",
    founders: [
      {
        name: "Alisha Merchant",
        role: "PM",
        image: "/founders/s25/alisha.png",
        bio: "Alisha studied cinema and media studies at USC with minors in health innovation and social advocacy. She has worked across health-tech consulting, policy, and project management.",
        linkedin: "https://www.linkedin.com/in/alisha-mer/",
      },
      {
        name: "Devin Hayden",
        role: "Designer",
        image: "/founders/s25/devin.png",
        bio: "Devin studies cognitive science at USC and is a product designer. He has built products across startups and enterprise, including work at Trimble and NRG.",
        linkedin: "https://www.linkedin.com/in/devin-hayden/",
      },
      {
        name: "Bona Suh",
        role: "Developer",
        image: "/founders/s25/bona.png",
        bio: "Bona studies computer science and interactive media at USC. She has built products in LavaLab and leads large-scale creative and startup initiatives through Spark SC.",
        linkedin: "https://www.linkedin.com/in/bonasuh/",
      },
      {
        name: "Anisha Chitta",
        role: "Developer",
        image: "/founders/s25/anisha.png",
        bio: "Anisha studies CS and business at USC and builds across AI and large-scale systems. She has worked at Atlassian and developed ML models and data systems through USC research.",
        linkedin: "https://www.linkedin.com/in/anisha-chitta/",
      },
    ],
  },
  {
    id: "trifect",
    name: "Trifect",
    description: "Match with the perfect 3PL partner for your business in minutes, not months.",
    longDescription:
      "Trifect is an AI-powered marketplace solving one of the most painful problems in logistics: matching businesses with the right 3PL. Today, the industry is highly fragmented, with over 70,000 3PLs operating at roughly 70% capacity and no centralized system to evaluate fit. As a result, businesses spend months vetting providers, often ending up with suboptimal partnerships. Trifect fixes this by aggregating deep operational data on thousands of 3PLs and using AI to intelligently match businesses based on their exact needs. By replacing manual search and guesswork with precise, data-driven matching, we reduce time to partnership, improve outcomes, and unlock unused capacity across the logistics ecosystem.",
    product:
      "Trifect is an AI-driven platform that matches businesses with their ideal 3PL partner. During onboarding, we collect key operational inputs such as shipping volumes, product dimensions, tech stack, and fulfillment requirements. Our system then dynamically asks follow-up questions using an LLM to refine understanding and ensure high-confidence matches. The platform outputs a curated set of best-fit 3PLs, ranked by compatibility. For 3PLs, Trifect delivers highly qualified, ready-to-convert leads that align with their operational strengths and available capacity. Businesses use the platform for free, while Trifect monetizes through a success-based commission on signed contracts.",
    logo: "/startup-logos/trifect.png",
    batch: "S25",
    industry: "Commerce",
    website: "",
    tags: ["AI", "Marketplace", "E-Commerce"],
    stage: "",
    founders: [
      {
        name: "Max Young",
        role: "PM",
        image: "/founders/s25/max.png",
        bio: "Founder and USC entrepreneurship student with experience building M.Y. Distributors and working with startups and investors at Refundid, Rainfall, and Salesforce Ventures.",
        linkedin: "https://www.linkedin.com/in/maxyoung10/",
      },
      {
        name: "Esther Kim",
        role: "Designer",
        image: "/founders/s25/esther.png",
        bio: "Product Designer and Prototyper @ USC Iovine Young Academy.",
        linkedin: "https://www.linkedin.com/in/esther-kim-75090320b/",
      },
      {
        name: "Sarah Fan",
        role: "Developer",
        image: "/founders/s25/sarah.png",
        bio: "CS at USC (Presidential Scholar). Previously software engineer at SpaceX (Starshield) and Northrop Grumman.",
        linkedin: "https://www.linkedin.com/in/sarah-fan-70400a241/",
      },
      {
        name: "Charles Gao",
        role: "Developer",
        image: "/founders/s25/charles.png",
        bio: "Incoming SWE @ Salesforce. Co-founder and CTO @ Gleame.",
        linkedin: "https://www.linkedin.com/in/csgao/",
      },
    ],
  },
  {
    id: "topaz",
    name: "Topaz",
    description: "Loyalty management software that makes rewards simple for customers and effortless for restaurants.",
    longDescription:
      "Small restaurants struggle to create and manage effective loyalty programs due to limited time, resources, and high costs, while customers are left juggling fragmented reward systems. Topaz simplifies this by providing an all-in-one, easy-to-use platform that centralizes loyalty for customers and enables restaurants to design, customize, and track rewards effortlessly. By making loyalty programs more accessible and data-driven, Topaz helps businesses increase retention and build stronger customer relationships.",
    product:
      "Topaz is a digital loyalty platform designed for quick-service restaurants that replaces traditional punch cards with a seamless, app-based experience. Customers can store all their rewards in one place and earn points or stamps instantly by scanning a QR code, while restaurants can easily create customizable loyalty programs, design branded reward cards, and track customer engagement through built-in analytics.",
    logo: "/startup-logos/topaz.png",
    batch: "F24",
    industry: "Restaurant",
    website: "",
    tags: ["B2B", "B2C","SaaS", "Restaurant"],
    stage: "",
    founders: [
      {
        name: "Mira Bhatt",
        role: "PM",
        image: "/founders/f24/mira.png",
        bio: "Mira studies business and AI at USC and builds products across fintech and consumer. She has worked in product at American Express and co-built Topaz through LavaLab.",
        linkedin: "https://www.linkedin.com/in/mira-bhatt-/",
      },
      {
        name: "Sarah Kwang",
        role: "Designer",
        image: "/founders/f24/sarah.png",
        bio: "Sarah is a designer with hands-on experience in creative design at Red Light Management and at other small-scale brand and design studios in Los Angeles. She works across branding, graphic, motion, UI/UX, and experience design, crafting user-centered solutions and compelling visual stories.",
        linkedin: "https://www.linkedin.com/in/sarah-kwang/?skipRedirect=true",
      },
      {
        name: "Christine Lai",
        role: "Developer",
        image: "/founders/f24/christine.png",
        bio: "Christine studies CS, design, and business at USC Iovine & Young Academy. She has worked across ML, product design, and hardware, including at Fenty Beauty (LVMH) and Code the Change.",
        linkedin: "https://www.linkedin.com/in/chrstnlai/",
      },
      {
        name: "Isabella Bernhardt Eiliya",
        role: "Developer",
        image: "/founders/f24/isabella.png",
        bio: "Isabella studies ECE at USC and builds across AI and full-stack systems. She has worked on LLM applications at Medtronic and co-developed Topaz, a rewards platform for restaurants.",
        linkedin: "https://www.linkedin.com/in/isabella-eiliya-a147922b4/",
      },
    ],
  },
  {
    id: "lattice",
    name: "Lattice",
    description: "Leveraging AI to streamline chemical research & development.",
    longDescription:
      "Lattice solves a deeply flawed step in the chemical synthesis and manufacturing process.  Most chemical companies spend $100,000s annually on patent lawyers to learn if subject chemicals have already been patented. Not only is this a colossal waste of money, but it pushes back timelines on important chemical and drug development. Lattice uses a proprietary AI model to convert chemical patents into a machine-readable code, so we can deliver priceless knowledge to chemists at the click of a button.",
    product:
      "Lattice streamlines chemical R&D by revealing if a chemical has already been patented and guiding chemists to pivot. It does this using a multi-modal AI pipeline that converts images and english text from chemical patent documents into machine-readable code.",
    logo: "/startup-logos/lattice.png",
    batch: "F24",
    industry: "AI / ML",
    website: "",
    tags: ["Chemical Synthesis", "Chemical Patent","B2B"],
    stage: "",
    founders: [
      {
        name: "Joseph Solomon",
        role: "PM",
        image: "/founders/f24/joseph.png",
        bio: "Joseph is a seasoned product manager, currently a Senior Consultant at 180 Degrees. Joseph is also USC Merit Scholar and Dean’s List Scholar.",
        linkedin: "https://www.linkedin.com/in/joseph--solomon/",
      },
      {
        name: "Bodie Currier",
        role: "Designer",
        image: "/founders/f24/bodie.png",
        bio: "Bodie is a GTM Engineer at Profound, where he builds visibility and optimization tools for the marketing platform. He has 4 years of experience shipping AI products, specializing in artificial memory, personality, and user interaction.",
        linkedin: "https://www.linkedin.com/in/bodiecurrier/",
        twitter: "https://x.com/BodieCurrier"
      },
      {
        name: "Evan Adami",
        role: "Developer",
        image: "/founders/f24/evan.png",
        bio: "Evan is a talented developer studying Computer Science at USC. He is the Co-President of QuantSC and a SWE intern at Hemut (YC X25)",
        linkedin: "https://www.linkedin.com/in/evan-adami-16b98a290/",
      },
      {
        name: "Shruti Nadala",
        role: "Developer",
        image: "/founders/f24/shruti.png",
        bio: "Shruti is a CECS student and talented developer. After LavaLab she interned at Wildcard, and is now the Vice President of iOSC and a member of ShiftSC.",
        linkedin: "https://www.linkedin.com/in/shruti-natala/",
      },
    ],
  },
  {
    id: "glance",
    name: "Glance",
    description: "AI-powered documentation platform that captures work and distributes progress context across teams.",
    longDescription:
      "Glance is an AI-powered workplace companion that automatically captures work as it happens and converts it into continuously updated progress summaries without requiring manual input. Teams today rely on status updates, check-ins, and fragmented communication to understand progress, often working from information that is delayed or incomplete. By observing workflows and inferring what is being worked on, what has changed, and what may be at risk, Glance gives teams a shared, always-accurate picture of progress in real time. This eliminates reporting overhead, reduces misalignment across teams, and enables faster, better-informed decisions grounded in what’s actually happening, not what was last reported.",
    product:
      "Glance provides a documentation layer that runs in the background alongside ongoing work. It captures activity signals, interprets progress and changes, and converts them into structured, continuously updated summaries. View real-time progress, track how work evolves, and surface risks as they emerge. The system maintains a clear, living record of work, giving teams a reliable source of truth without interrupting execution.",
    logo: "/startup-logos/glance.png",
    batch: "F24",
    industry: "AI / ML",
    website: "https://glance-landing.vercel.app/",
    tags: ["AI", "B2B"],
    stage: "",
    founders: [
      {
        name: "Jonathan Powers",
        role: "PM",
        image: "/founders/f24/jonathan.png",
        bio: "Founded  a seven-figure e-commerce brand, before leading growth at Wand, a PC gaming platform trusted by 40 million players. Jon specializes in conversion-driven product strategy and scaling social presence, combining creative storytelling with performance marketing.",
        linkedin: "https://www.linkedin.com/in/jonbpowers/",
        twitter: "https://x.com/jonnpowers",
      },
      {
        name: "Josephine Onggowarsito",
        role: "Designer",
        image: "/founders/f24/josephine.png",
        bio: "Previously Product Designer at Polychain Capital, designing core trading and onboarding experiences for Superstack. Co-founded Heat, a crypto prediction market that won $30K across hackathons. Her background spans XR interaction design, game development, and a freelance design practice serving 50+ startups. Josephine studies Arts, Technology, and Business of Innovation at USC's Iovine Young Academy.",
        linkedin: "https://www.linkedin.com/in/josephine-onggowarsito/",
        twitter: "https://x.com/josephineonggo",
      },
      {
        name: "Daniel Gao",
        role: "Developer",
        image: "/founders/f24/daniel.png",
        bio: "Incoming Software Engineer at Amazon, where he previously interned on Payments Technology. Co-founded Glance and led engineering at TroyLabs, USC's flagship startup accelerator. A Kleiner Perkins and 8VC finalist, Comma Capital fellow, and multiple-time hackathon winner — including 1st place at USC x Anthropic. Daniel studies Computer Science and Business at USC.",
        linkedin: "https://www.linkedin.com/in/danielgao20/",
        twitter: "https://x.com/danielgaoo",
      },
      {
        name: "David Han",
        role: "Developer",
        image: "/founders/f24/david.png",
        bio: "Incoming Software Engineering Intern at Bloomberg. Previously at Activision Blizzard, where he designed and built a full-stack anticheat console for Call of Duty supporting millions of real-time detections — shipped with Black Ops 7 credits to his name. Co-founded Glance and founded Batchr, a restaurant operating system, through USC's startup incubator. David studies Computer Science at USC.",
        linkedin: "https://www.linkedin.com/in/davidhanusc/",
        twitter: "https://x.com/aznduck",
      },
    ],
  },
  {
    id: "due",
    name: "Due",
    description: "Transforming homework into a dynamic learning experience.",
    longDescription:
      "Due is an AI-powered, dynamic homework platform for middle school students that allows them to interact with their (once static) homework, improving the critical thinking and learning process. Additionally, Due allows teachers to gain crucial insights into student understanding through metrics like frequently asked questions, keywords, etc., to modify their curriculum.",
    product:
      "Due asks teachers to upload a copy of their homework, which it converts to a homework activity for students. Students can then ask as many questions to Due as they work through their homework. Due populates a teacher dashboard, providing a fingerprint of their classroom which only gets better overtime. Due flags at-risk students, shows teachers the topics which students get confused on the most, and more, so that teachers can modify their curriculum accordingly.",
    logo: "/startup-logos/due.png",
    batch: "F24",
    industry: "EdTech",
    website: "",
    tags: ["Education", "AI", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Sky Lam",
        role: "PM",
        image: "/founders/f24/sky.png",
        bio: "Incoming Product Deployment Strategist at Persona. A people first product manager with a special interest in hardware.",
        linkedin: "https://www.linkedin.com/in/skylam-justachillguy/",
      },
      {
        name: "Lauryn Kinsella",
        role: "Designer",
        image: "/founders/f24/lauryn.png",
        bio: "Lauryn is a designer who cares about visual craft and design community. She is designing at Stripe and swsh, and building community at Figma and Verci!",
        linkedin: "https://www.linkedin.com/in/laurynkinsella/",
        twitter: "https://x.com/laurynkinsella?s=21",
      },
      {
        name: "Amrita Arun",
        role: "Developer",
        image: "/founders/f24/amrita.png",
        bio: "Amrita is a CS student and incoming SWE intern at Tradeweb, interested in building thoughtful, user-facing products. Her work has largely been in edtech, where she’s worked across full-stack engineering and early product development on tools designed for real classroom use. She’s currently exploring mobile app development and diving deeper into product and interaction design.",
        linkedin: "https://www.linkedin.com/in/amrita-arun/",
        twitter: "https://x.com/amrita__arun",
      },
      {
        name: "Kristi Wu",
        role: "Developer",
        image: "/founders/f24/kristi.png",
        bio: "Incoming Business Development & Consulting Associate at HighPoint Associates. Kristi brings experience at the intersection of business strategy and computer science.",
        linkedin: "https://www.linkedin.com/in/kristi-wu/",
      },
    ],
  },
  {
    id: "tally",
    name: "Tally",
    description: "AI inventory manager.",
    longDescription:
      "Tally is an autonomous AI inventory manager that monitors your stock levels in real time, alerts you when materials run low, and autonomously reorders inventory on your behalf — so you're never caught short. The more you use it, the smarter it gets, using ML forecasting to predict demand and stay one step ahead.",
    product:
      "Tally uses voice and browser agents that act on your behalf to manage the full inventory lifecycle. Users define product recipes linking materials to variants, connect their storefronts (Shopify, Etsy, ShipStation, and more), and Tally's agents autonomously monitor levels, trigger reorders with suppliers, and surface fulfillment tasks — all without manual input. The system learns your ordering patterns over time to make increasingly accurate demand forecasts.",
    logo: "/startup-logos/tally.png",
    batch: "F24",
    industry: "AI / ML",
    website: "https://keeptallyapp.com/",
    tags: ["B2B", "AI", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Haha Shi",
        role: "PM",
        image: "/founders/f24/haha.png",
        bio: "AI Product Manager @ Optro | Computational Neuroscience + AI @ USC | Presidential Scholar",
        linkedin: "https://www.linkedin.com/in/yumeishi/",
      },
      {
        name: "Megan Phi",
        role: "Designer",
        image: "/founders/f24/megan.png",
        bio: "Product Designer @ Ditto | Prev. @ Altruist, Cisco | Industrial and Systems Engineering @ USC",
        linkedin: "https://www.linkedin.com/in/megan-phi/",
        twitter: "https://x.com/meganvphi",
      },
      {
        name: "Mohamed Ahmed",
        role: "Developer",
        image: "/founders/f24/mohamed.png",
        bio: "Product Engineer @ Polymarket",
        linkedin: "https://www.linkedin.com/in/0xmo/",
        twitter: "https://x.com/ruinedbymo",
      },
      {
        name: "Jeremy Sedillo",
        role: "Developer",
        image: "/founders/f24/jeremy.png",
        bio: "Prev SWE @ Amazon",
        linkedin: "https://www.linkedin.com/in/jeremy-sedillo/",
        twitter: "https://x.com/jerrmsaid",
      },
    ],
  },
  {
    id: "lumen",
    name: "Lumen",
    description: "Highlighting user voices.",
    longDescription:
      "Lumen is an AI-powered product insights platform that helps teams make sense of fragmented user feedback by turning scattered signals into clear, actionable strategy. Today, feedback lives across emails, support tickets, social media, and in-app messages, forcing product teams to spend hours manually piecing together what users actually want, often missing key trends and building the wrong features as a result. Lumen solves this by automatically collecting feedback from all channels, using AI to categorize and consolidate similar insights, and surfacing the most important patterns in real time. Instead of drowning in noise, teams get a unified, crystal-clear view of user needs, enabling them to prioritize effectively, move faster, and build products that truly resonate.",
    product:
      "Lumen aggregates and analyzes user feedback from across the web and your product in one unified interface. It automatically collects feedback from sources like social media, support tickets, and in-app submissions, then uses AI to categorize and consolidate similar insights into clear trends. Teams can instantly identify the most requested features, filter feedback by recency, type, or source, and use natural language search to dive into specific user concerns. By transforming scattered feedback into structured, actionable insights, Lumen enables product teams to quickly understand what matters most to their users and make smarter, faster product decisions.",
    logo: "/startup-logos/lumen.png",
    batch: "F24",
    industry: "AI / ML",
    website: "",
    tags: ["AI", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Atticus Kim",
        role: "PM",
        image: "/founders/f24/atticus.png",
        bio: "Atticus studies business and AI at USC and builds across product and strategy. Previously interned at NVIDIA and Citadel.",
        linkedin: "https://www.linkedin.com/in/atticuskim/",
      },
      {
        name: "Yeji Seo",
        role: "Designer",
        image: "/founders/f24/yeji.png",
        bio: "Yeji is a product and brand designer at USC IYA. She has worked on large-scale consumer products, including redesigning a platform with 5M+ users and building at early-stage startups.",
        linkedin: "https://www.linkedin.com/in/faithyejiseo/",
      },
      {
        name: "Jerry Zhang",
        role: "Developer",
        image: "/founders/f24/jerry.png",
        bio: "Jerry is co-founder and CEO of Lemma (YC F25), building continuous learning systems for AI agents. He studied CS and business at USC.",
        linkedin: "https://www.linkedin.com/in/jerry-n-zhang/",
      },
      {
        name: "Naysa Bhargava",
        role: "Developer",
        image: "/founders/f24/naysa.png",
        bio: "Naysa is a software engineer at USC. ASD intern at Google, with experience across AI, full-stack development, and research.",
        linkedin: "https://www.linkedin.com/in/naysa-bhargava/",
      },
    ],
  },
  {
    id: "aro",
    name: "Aro",
    description: "No-code typesetting solution, simplifying complex document creation.",
    longDescription:
      "Aro is a no-code platform that simplifies the creation of complex, structured documents. Today, professionals rely on tools like LaTeX or manual formatting to produce high-quality outputs, which is time-consuming, error-prone, and inaccessible to most users. By removing the need to write formatting code, Aro makes professional-grade formatting accessible to a much broader audience.",
    product:
      "Aro provides a no-code workflow for creating and managing complex documents. Users can create, edit, and organize documents through an intuitive interface, while the platform automatically handles formatting and layout. Collaborators can work together on documents, track changes, and generate clean, structured outputs without dealing with code. This streamlines the entire document creation process and eliminates the need for traditional typesetting tools.",
    logo: "/startup-logos/aro.png",
    batch: "S24",
    industry: "Consumer",
    website: "https://aroeditor.io",
    tags: ["B2C", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Cody Chen",
        role: "PM",
        image: "/founders/s24/cody.png",
        bio: "CS and Business at USC, Prev. PM @ Tesla, Intuit. Passionate about fostering connection between people through product, community, and technology. Love stories that stick, Jasmine tea, and YouTube.",
        linkedin: "https://www.linkedin.com/in/codyachen/",
      },
      {
        name: "Uyen Hoang",
        role: "Designer",
        image: "/founders/s24/uyen.png",
        bio: "Product Design @ USC. I design to integrate & elevate ideas– blending my own with others' to turn the boring into the striking & complexity into clarity.",
        linkedin: "https://www.linkedin.com/in/nhatuyenhoang/",
      },
      {
        name: "Cole Gawin",
        role: "Developer",
        image: "/founders/s24/cole.png",
        bio: "Co-founder + CTO @ Lemma (YC F25), Prev. Cogsci & CS @ USC. I'm a product engineer and AI/ML scientist focused on bridging the gap between machine intelligence and human potential. Currently on leave from USC and building Lemma (YC F25), the continuous learning layer for AI agents.",
        linkedin: "https://www.linkedin.com/in/colegawin/",
        twitter: "https://x.com/colegawin_",
      },
      {
        name: "Sunay Sanghani",
        role: "Developer",
        image: "/founders/s24/sunay.png",
        bio: "Data @ Enigma. I am excited and passionate about the power of data to inform business decisions and drive insights across different domains and applications.",
        linkedin: "https://www.linkedin.com/in/sunaysanghani/",
      },
    ],
  },
  {
    id: "axle",
    name: "Axle",
    description: "Marketplace for automotive parts.",
    longDescription:
      "Axle is a Marketplace platform that connects car part vendors and suppliers. It automatically schedules car part orders, manages part inventory and predicts order requests.",
    product:
      "As a two sided marketplace there are two workflows. Vendors upload their information including their inventory which is tracked in our platform. Everytime an order request comes into the marketplace, the platform automatically handles the order and the part is shipped out. From a buyers perspective, they simply upload their information including invoices, address and part logs. ",
    logo: "/startup-logos/axle.png",
    batch: "S24",
    industry: "Automotive",
    website: "",
    tags: ["B2B", "SaaS", "Marketplace"],
    stage: "",
    founders: [
      {
        name: "Advik Unni",
        role: "PM",
        image: "/founders/s24/advik.png",
        bio: "Incoming ML @ Uber. Prev @ Google Chrome AI, IBM. Sidequesting & building.",
        linkedin: "www.linkedin.com/in/Advik-unni",
      },
      {
        name: "Avery Park",
        role: "Designer",
        image: "/founders/s24/avery.png",
        bio: "Avery studied cognitive science at USC. She has worked on web and product design through Innovative Design, focusing on intuitive, user-centered experiences.",
        linkedin: "https://www.linkedin.com/in/nhatuyenhoang/",
      },
      {
        name: "Rak Thuraga",
        role: "Developer",
        image: "/founders/s24/rak.png",
        bio: "Prev AI & Full Stack SWE Intern @ GM | Applied and Computational Math + CS @ USC.",
        linkedin: "https://www.linkedin.com/in/rakshith-thuraga/",
      },
      {
        name: "Angela Nguyen",
        role: "Developer",
        image: "/founders/s24/angela.png",
        bio: "Angela studied computer science at USC and is now a software engineer at Apple. She works on Siri, including ChatGPT integrations, and previously interned at Apple across multiple teams.",
        linkedin: "https://www.linkedin.com/in/angelatramnguyen/",
      },
    ],
  },
  {
    id: "cartpool",
    name: "Cartpool",
    description: "Save on international shopping by pooling orders and splitting shipping costs.",
    longDescription:
      "Cartpool helps consumers in the U.S. access international products without the burden of high shipping costs and limited payment options. Today, global shopping is more accessible than ever, but expensive international shipping fees often double or triple the total cost at checkout, causing many users to abandon their purchases. This problem is especially common among students and young consumers who frequently purchase items from overseas brands, including fashion, beauty, and niche products. While group ordering could reduce costs, coordinating with others is difficult and inefficient. Cartpool solves this by creating a centralized platform where users can pool orders from the same international retailer. By aggregating demand, we reduce per-user shipping costs while simplifying the entire process—from payment to delivery. Users can also share their order links to invite others, further lowering costs and increasing accessibility to global products.",
    product:
      "Cartpool is a platform that allows users to shop internationally without paying full shipping costs. Users simply paste a product link from a supported international retailer, pay for their item upfront, and Cartpool groups their order with others purchasing from the same source. Once the group is finalized, shipping costs are split among all participants. The platform also generates shareable links so users can invite friends or others to join their order, increasing group size and reducing costs further. After items arrive in the U.S., Cartpool works with fulfillment partners to distribute orders domestically at low rates. Cartpool simplifies international shopping into three steps: Shop → Pool → Save",
    logo: "/startup-logos/cartpool.png",
    batch: "S24",
    industry: "Consumer",
    website: "https://cartpool.vercel.app/",
    tags: ["E-commerce", "Logistics", "Marketplace"],
    stage: "",
    founders: [
      {
        name: "Zhamaika Mussaibekova",
        role: "PM",
        image: "/founders/s24/zhamaika.png",
        bio: "Zhamilya studies cognitive science and linguistics at USC and works in product. She helps lead entrepreneurship initiatives through Spark SC.",
        linkedin: "https://www.linkedin.com/in/zhamaika/",
      },
      {
        name: "Kezia Leung",
        role: "Designer",
        image: "/founders/s24/kezia.png",
        bio: "Kezia is a freelance product designer and studied cognitive science and computer programming. She aims to design products to empower people. Kezia was going to pursue product management; however, she decided to take a year to teach English and help NGOs in Vietnam. She will be returning to NYC.",
        linkedin: "https://www.linkedin.com/in/kezialeung/",
      },
      {
        name: "Minnah Basit",
        role: "Developer",
        image: "/founders/s24/minnah.png",
        bio: "Minnah Basit studies Computer Science at the University of Southern California and a former Software Development Engineer Intern at Amazon Web Services. She has experience across full-stack development and data analysis, having worked at Scale AI. She is passionate about building products that make global access more affordable and connected.",
        linkedin: "https://www.linkedin.com/in/minnahbasit/",
      },
      {
        name: "Anandini Bassi",
        role: "Developer",
        image: "/founders/s24/anandini.png",
        bio: "Anandini Bassi is a Software Development Engineer at Amazon Web Services and a Computer Science graduate from USC. She has experience building scalable, user-focused systems across both industry and nonprofit spaces, including developing a healthcare supply matchmaking platform using React and AWS.",
        linkedin: "https://www.linkedin.com/in/angelatramnguyen/",
      },
    ],
  },
  {
    id: "sequence",
    name: "Sequence",
    description: "An integrated and centralized platform for all varieties of choose-your-own adventure stories.",
    longDescription:
      "Sequence is a no-code platform for interactive, choice-driven storytelling. Creating branching narratives has always required technical skill or inefficient tools, which discourage the majority of writers who just want to tell compelling stories. Meanwhile, readers have no dedicated home for discovering this genre. Sequence bridges both sides by making creation accessible to any writer and building a community where fans of choose-your-own-path stories can find and share immersive experiences.",
    product:
      "Sequence provides a drag-and-drop story editor and a reader-facing discovery platform in one place. Writers use the no-code canvas to build branching narratives, connect story nodes, and publish without writing a single line of code. Readers browse and play through choice-driven stories directly on the platform, with their decisions shaping the outcome. The tight integration between creator tools and the reader experience fosters a community around the genre.",
    logo: "/startup-logos/sequence.png",
    batch: "S24",
    industry: "EdTech",
    website: "https://sequencestories.com/",
    tags: ["Publishing", "Media", "Marketplace"],
    stage: "",
    founders: [
      {
        name: "Fatema Bhaiji",
        role: "PM",
        image: "/founders/s24/fatema.png",
        bio: "Fatema majored in Narrative Studies with emphases on Islamic and Spanish-language media. She has worked across industries from entertainment at Paramount to tech at Amazon. She is passionate about book-screen adaptations, making diverse literature & film accessible to underrepresented communities, and experimenting with creative technology as applied to the media and publishing industries. Post-grad, she will study across four countries in the European Union as an Erasmus Mundus Scholar to pursue an international joint masters in Children’s Literature, Media, and Cultural Entrepreneurship.",
        linkedin: "https://www.linkedin.com/in/fatema-bhaiji-0b218423b/",
      },
      {
        name: "Jacqueline Sung",
        role: "Designer",
        image: "/founders/s24/jacqueline.png",
        bio: "Jacqueline majored in Arts, Technology, and the Business of Innovation under the Iovine and Young Academy. She works across various design mediums, from branding, graphic design, motion graphics, and illustration. She’s worked as a marketing intern at an independent art studio (Studio Unto) and also at a marketing agency (Dentsu). She is all about indie game development and currently leads visual development and marketing for her capstone project of Game Night Studios (@thegamenightstudios on TikTok, Instagram, and YouTube).",
        linkedin: "https://www.linkedin.com/in/jacqueline-sung-83b540248/",
      },
      {
        name: "Jasmine Yip",
        role: "Developer",
        image: "/founders/s24/jasmine.png",
        bio: "Jasmine is a Computer Science major with previous software engineering experience at LinkedIn, Tessera Labs (a16z-backed start up), and Serato. She works across different disciplines of software engineering, including front-end, back-end, mobile, and AI/ML. She is passionate about problems at the intersection of AI, infrastructure, and product.",
        linkedin: "https://www.linkedin.com/in/jasmine-yyy/",
      },
      {
        name: "Paul Somodi",
        role: "Developer",
        image: "/founders/s24/paul.png",
        bio: "Paul is a Software Engineering at Goldman Sachs with a B.S. and M.S. in Computer Science from the University of Southern California. He works across different disciplines of software engineering, including machine learning, software engineering, and data science. He is passionate about using engineering to make the world a better place.",
        linkedin: "https://www.linkedin.com/in/paulsomodi/",
      },
    ],
  },
  {
    id: "activ",
    name: "Activ",
    description: "The social network for fitness.",
    longDescription:
      "Activ is a social fitness platform built for gym-goers who want more than just a workout tracker. The core problem is that many people struggle to find a fitness community where they can learn, stay motivated, and remain accountable over time. Activ addresses that by creating a dedicated social network for gym life, where users can connect with others, discover routines, share progress, and build consistency through community. Activ is designed to make fitness feel less isolated and more motivating by turning workouts into a shared experience centered around community, motivation, and personal growth.",
    product:
      "Activ is a mobile platform that combines workout tracking, scheduling, social posting, and community discovery into one app designed specifically for fitness. Users can create and schedule workouts, track activity and progress over time, explore other people’s routines and exercises, save popular workouts, and engage with fitness communities built around shared goals and interests. Premium features allow Activ users to deepen engagement with features like leaderboards, instructional videos, and richer analytics to boost their fitness journeys.",
    logo: "/startup-logos/activ.png",
    batch: "F23",
    industry: "Consumer",
    website: "",
    tags: ["Fitness", "Health", "B2C"],
    stage: "",
    founders: [
      {
        name: "Bryan Phillips",
        role: "PM",
        image: "/founders/f23/bryan.png",
        bio: "Portfolio management @ BlackRock. Bryan's experience revolves around market research, breaking down financial markets, and communicating investment strategy.",
        linkedin: "https://www.linkedin.com/in/bryan-phillips12/",
      },
      {
        name: "Jiwon Lee",
        role: "Designer",
        image: "/founders/f23/jiwon.png",
        bio: "Jiwon is a product designer focused on UX. She currently works as a UX designer at 7-Eleven and previously designed at CNN, building consumer-facing digital experiences.",
        linkedin: "https://www.linkedin.com/in/jiwonlee01/",
      },
      {
        name: "Reza Banankhah",
        role: "Developer",
        image: "/founders/f23/reza.png",
        bio: "Reza is a software engineer at Roblox. He studied CS and business at USC and previously worked on backend systems and AI products at startups and fintech companies.",
        linkedin: "https://www.linkedin.com/in/rbanankhah/",
      },
      {
        name: "Yifei Lu",
        role: "Developer",
        image: "/founders/f23/yifei.png",
        bio: "Yifei studies CS at USC and builds across backend systems and product engineering. She has interned at Meta and Gemini and developed products through LavaLab.",
        linkedin: "https://www.linkedin.com/in/yifei-lu-usc/",
      },
    ],
  },
  {
    id: "codeflow",
    name: "CodeFlow",
    description: "Automatically turn your codebase into clear, up-to-date documentation for your entire team.",
    longDescription:
      "Engineering teams move fast, but documentation rarely keeps up, making onboarding slow and knowledge fragmented. As codebases grow, critical context lives in scattered files or in the heads of a few engineers. CodeFlow solves this by turning the codebase itself into a living source of truth that stays continuously up to date.",
    product:
      "CodeFlow connects to your repositories and automatically generates structured, human-readable documentation from your code. It maps system architecture, explains how components interact, and creates onboarding guides for new engineers. As the code evolves, documentation updates in real time, so teams always have an accurate understanding of their systems.",
    logo: "/startup-logos/codeflow.png",
    batch: "S23",
    industry: "AI / ML",
    website: "",
    tags: ["DevTools", "B2B", "SaaS"],
    stage: "",
    founders: [
      {
        name: "Mandika Swartz",
        role: "PM",
        image: "/founders/s23/mandika.png",
        bio: "Mandika is the CEO and co-founder of Halo Health, building an AI-powered operating layer for private medical practices across charting, call centers, and revenue cycle workflows. He started Halo alongside his best friend and fellow LavaLab alum, growing the company into a multi-million ARR business while working closely with hundreds of providers to streamline front- and back-office operations.",
        linkedin: "www.linkedin.com/in/mandikaswartz",
        twitter: "https://x.com/MandikaSwartz",
      },
      {
        name: "Elizabeth Fernandes",
        role: "Designer",
        image: "/founders/s23/elizabeth.png",
        bio: "Elizabeth combines design, research, and strategy. At USC Iovine & Young Academy, she built products and worked with companies such as Remi (YC-backed), Spectro Cloud, EY, and Impossible Foods.",
        linkedin: "https://www.linkedin.com/in/elizfern/",
      },
      {
        name: "Anisha Reddy",
        role: "Developer",
        image: "/founders/s23/anisha.png",
        bio: "Anisha studied computer science at USC and is now at Carnegie Mellon for AI. She has worked across research, teaching, and product development, including working on healthcare innovation through the Gehr Center.",
        linkedin: "https://www.linkedin.com/in/anishareddy/",
      },
      {
        name: "Winston Zhang",
        role: "Developer",
        image: "/founders/s23/winston.png",
        bio: "Winston studied math and computer science at USC and now works as a software engineer at Citadel. Previously, he built systems at Argument and contributed to formal verification work at OpenAI.",
        linkedin: "https://www.linkedin.com/in/hanting-zhang/",
      },
    ],
  },
  {
    id: "documate",
    name: "Documate",
    description: "Simplifying hardware documentation.",
    longDescription:
      "Documate aims to solve info overload for PDF-manual based industry, most notably the hardware industry.",
    product:
      "Documate is a documentation tool that generates a Docusaurus-like website, given a PDF. Integrates GPT for semantic searches and chat explanation.",
    logo: "/startup-logos/documate.png",
    batch: "S23",
    industry: "Hardware",
    website: "",
    tags: ["AI", "SaaS", "B2B", "B2C"],
    stage: "",
    founders: [
      {
        name: "Chris Pramana",
        role: "PM",
        image: "/founders/s23/chris.png",
        bio: "Product design @ Ramp | 8VC fellow",
        linkedin: "https://www.linkedin.com/in/capramana/",
        twitter: "https://x.com/chrispramana",
      },
      {
        name: "Allison Huang",
        role: "Designer",
        image: "/founders/s23/allison.png",
        bio: "CS, design, and business at USC | Presidential scholar",
        linkedin: "https://www.linkedin.com/in/allisoncyhuang/",
        twitter: "https://x.com/allisoncyhuang",
      },
      {
        name: "Eric Zhong",
        role: "Developer",
        image: "/founders/s23/eric.png",
        bio: "GPU Architect @ NVIDIA",
        linkedin: "https://www.linkedin.com/in/erictzhong/",
      },
      {
        name: "Steve Vott",
        role: "Developer",
        image: "/founders/s23/steve.png",
        bio: "USC Computer Science, Applied Math",
        linkedin: "https://www.linkedin.com/in/steve-vott-2505b41b1/",
      },
    ],
  },
  {
    id: "sticker",
    name: "Sticker",
    description: "Create challenges with friends to accomplish goals.",
    longDescription:
      "Combatting the common problem of failing to achieve goals, Sticker is a mobile app that helps friends keep track of their goals together. Friends compete with each other on shared goals. Sticker is a Strava for any type of activity.",
    product:
      "Sticker makes it possible to customize any type of goal, such as working towards benching XXkg or applying to more jobs. Once a goal is created, users can add their friends as competitors, log progress over time, and see the leaderboard for the challenge once the goal is completed.",
    logo: "/startup-logos/sticker.png",
    batch: "S22",
    industry: "Consumer",
    website: "",
    tags: ["B2C"],
    stage: "",
    founders: [
      {
        name: "Xin Ma",
        role: "PM",
        image: "/founders/s22/xin.png",
        bio: "Incoming Strategy & Ops @ Revolut. Previously worked at fintech, healthtech, and greentech startups in product management, growth, and design roles. At USC, Xin is in World Bachelor in Business, a joint program between USC, HKUST, and Bocconi University.",
        linkedin: "https://www.linkedin.com/in/xxinyuema/",
      },
      {
        name: "Sophia Park",
        role: "Designer",
        image: "/founders/s22/sophia.png",
        bio: "Sophia studied design and applied arts at USC, focusing on visual design and creative development.",
        linkedin: "https://www.linkedin.com/in/sophiaypark/",
      },
      {
        name: "Sarah Liang",
        role: "Developer",
        image: "/founders/s22/sarah.png",
        bio: "Sarah studied computer science at USC and is a software engineer at Wells Fargo. She previously interned at Experian and led AthenaHacks.",
        linkedin: "https://www.linkedin.com/in/saraheliang/",
      },
      {
        name: "Wilson Lim Setiawan",
        role: "Developer",
        image: "/founders/s22/wilson.png",
        bio: "Wilson studied computer science at USC. He works across software and growth at Serta and has previously built at Goldman Sachs, Feathery, and Lafayette Square.",
        linkedin: "https://www.linkedin.com/in/wilsonlimsetiawan/",
      },
    ],
  }
];
