const members = [
  {
    name: "Sonya Alexis",
    role: "President",
    cohort: "Cohort S'25",
    image: "/founders/s25/sonya.png",
    url: "https://www.linkedin.com/in/sonya-alexis/",
  },
  {
    name: "Mannat Bawa",
    role: "Vice President",
    cohort: "Cohort F'25",
    image: "/founders/f25/mannat.png",
    url: "https://www.linkedin.com/in/mannatbawa/",
  },
  {
    name: "Bodie Currier",
    role: "Director of Curriculum",
    cohort: "Cohort F'24",
    image: "/founders/f24/bodie.png",
    url: "https://www.linkedin.com/in/bodiecurrier/",
  },
  {
    name: "Arnav Shah",
    role: "Director of PM",
    cohort: "Cohort S'25",
    image: "/founders/s25/arnav.png",
    url: "https://www.linkedin.com/in/arnav-ashah/",
  },
  {
    name: "Ben Flora",
    role: "Director of Design",
    cohort: "Cohort S'26",
    image: "/founders/s26/ben.png",
    url: "https://www.linkedin.com/in/benjaminflora/",
  },
  {
    name: "Ethan Palosh",
    role: "Director of Engineering",
    cohort: "Cohort S'25",
    image: "/founders/s25/ethan.png",
    url: "https://www.linkedin.com/in/ethanpalosh/",
  },
  {
    name: "Amrita Arun",
    role: "Director of External Community",
    cohort: "Cohort F'24",
    image: "/founders/f24/amrita.png",
    url: "https://www.linkedin.com/in/amrita-arun/",
  },
  {
    name: "Ronnie Cheung",
    role: "Alumni Director of Community",
    cohort: "Cohort S'26",
    image: "/founders/s26/ronnie.png",
    url: "https://www.linkedin.com/in/ronnie-cheung/",
  },
  {
    name: "Charles Gao",
    role: "Co-Director of Internal Community",
    cohort: "Cohort S'25",
    image: "/founders/s25/charles.png",
    url: "https://www.linkedin.com/in/csgao/",
  },
  {
    name: "Arin Jain",
    role: "Director of Industry Relations",
    cohort: "Cohort S'25",
    image: "/founders/s25/arin.png",
    url: "https://www.linkedin.com/in/arinjain1/",
  },
  {
    name: "Jo Choi",
    role: "Director of Publicity",
    cohort: "Cohort F'25",
    image: "/founders/f25/jo.png",
    url: "https://www.linkedin.com/in/joseph-jo-choi/",
  },
  {
    name: "Tongfei Zhu",
    role: "Director of Marketing",
    cohort: "Cohort S'25",
    image: "/founders/s25/tongfei.png",
    url: "https://www.linkedin.com/in/tongfeiz/",
  },
  {
    name: "Sania Gupta",
    role: "Director of Recruitment",
    cohort: "Cohort S'26",
    image: "/founders/s26/sania.png",
    url: "https://www.linkedin.com/in/sania-gupta/",
  },
];

export default members;
